<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

		public function getAvecCategorie(array $nom_categories)
		{
			# code...
			$qb = $this->createQueryBuilder('a');

			//on fait une jointure avec l'entite Categorie, avec pour alias <c>
			$qb ->join('a.categories', 'c')
				->where($qb->Expr()->in('c.nom', $nom_categories));

			// puis on filtre le nom des categories a l'aide d'un IN

			//et enfin on retourne le resultat
			return $qb->getQuery()->getResult(); 
		}
}
