
cert_incident:
    resource: "@CertIncidentBundle/Resources/config/routing.yml"
    prefix:   /

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cert_incident_admin_articles:
    resource: "@CertIncidentBundle/Resources/config/routing/articles.yml"
    prefix:   /admin/articles

admin_alerte_show:
    path:     /{id}/show
    defaults: { _controller: "CertIncidentBundle:Alerte:show" }

cert_user_admin_users:
    resource: "@CertUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users

fos_user_security_login:
    pattern:    /login
    defaults:    { _controller: CertUserBundle:Security:logoutin }

fos_user_security_check:
    pattern:    /login_check

fos_user_security_logout:
    pattern:    /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

cert_incident_admin_annonce:
    resource: "@CertIncidentBundle/Resources/config/routing/annonce.yml"
    prefix:   /admin/annonce

cert_incident_admin_vulnerabilite:
    resource: "@CertIncidentBundle/Resources/config/routing/vulnerabilite.yml"
    prefix:   /admin/vulnerabilite

cert_incident_admin_alerte:
    resource: "@CertIncidentBundle/Resources/config/routing/alerte.yml"
    prefix:   /admin/alerte