# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        symfony\Component\security\Core\User\User: plaintext
        Cert\UserBundle\Entity\User: sha512

    role_hierarchy:
        #un admin herite des droits d'expertinfo et de moderateur
        ROLE_ADMIN:       [ROLE_EXPERTINFO,ROLE_USER]
        #on garde ce role superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_EXPERTINFO,ROLE_ALLOWED_TO_SWITCH]

    providers:
        # notre nouveau fournisseur
        main:
            id:  fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # le pare-feu <<dev>>
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal pour le reste de notre site
        # on cree un pare-feu uniquement pour le formulaire
        main:
            pattern: ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /profile
            logout:
                path:    fos_user_security_logout
                target:   /incident
                invalidate_session: false
            remember_me:
                key:      %secret% #%secret% est un parametre de parameters.yml 

    access_control:
        - { path: ^/admin/*, roles: ROLE_SUPER_ADMIN, ip:127.0.0.1 }
        - { path: ^/admin/users, roles: ROLE_EXPERTINFO, ip:127.0.0.1 }
        - { path: ^/admin/annonce, roles: ROLE_ADMIN, ip:127.0.0.1 }
        - { path: ^/admin/alerte, roles: ROLE_ADMIN, ip:127.0.0.1 }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

