<?php

namespace Cert\IncidentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteRepository extends EntityRepository
{
}
