<?php

namespace Cert\IncidentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceImageRepository extends EntityRepository
{
}
