expert_incident:
    path:     /
    defaults: { _controller: "CertIncidentBundle:Incident:index" }

expert_incident_show:
    path:     /{id}/show
    defaults: { _controller: "CertIncidentBundle:Incident:show" }

expert_incident_new:
    path:     /new
    defaults: { _controller: "CertIncidentBundle:Incident:new" }

expert_incident_create:
    path:     /create
    defaults: { _controller: "CertIncidentBundle:Incident:create" }
    methods:  POST

expert_incident_edit:
    path:     /{id}/edit
    defaults: { _controller: "CertIncidentBundle:Incident:edit" }

expert_incident_update:
    path:     /{id}/update
    defaults: { _controller: "CertIncidentBundle:Incident:update" }
    methods:  [POST, PUT]

expert_incident_delete:
    path:     /{id}/delete
    defaults: { _controller: "CertIncidentBundle:Incident:delete" }
    methods:  [POST, DELETE]
