Cert\IncidentBundle\Entity\Vulnerabilite:
    type: entity
    table: vulnerabilite
    repositoryClass: Cert\IncidentBundle\Entity\VulnerabiliteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: '255'
        description:
            type: text
        impact:
            type: text
        solution:
            type: text
        reference:
            type: array
        source:
            type: text
        datepub:
            type: datetimetz
        dateModification:
            type: datetimetz
    manyToOne:
        user:
            targetEntity: \Cert\UserBundle\Entity\User
            inversedBy: vulnerabilites 
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
