admin_users:
    path:     /
    defaults: { _controller: "CertUserBundle:User:index" }

admin_users_show:
    path:     /{id}/show
    defaults: { _controller: "CertUserBundle:User:show" }

admin_users_new:
    path:     /new
    defaults: { _controller: "CertUserBundle:User:new" }

admin_users_create:
    path:     /create
    defaults: { _controller: "CertUserBundle:User:create" }
    methods:  POST

admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "CertUserBundle:User:edit" }

admin_users_update:
    path:     /{id}/update
    defaults: { _controller: "CertUserBundle:User:update" }
    methods:  [POST, PUT]

admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "CertUserBundle:User:delete" }
    methods:  [POST, DELETE]
