sdz_blog_homepage:
    path:     /hello/{name}
    defaults: { _controller: SdzBlogBundle:Default:index }

sdzblog_accueil:
    pattern:    /{page}
    defaults:    { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:  
        page:    \d*

sdzblog_voir:
    pattern:    /article/{id}
    defaults:    { _controller: SdzBlogBundle:Blog:voir }
    requirements:
        id:    \d+

sdzblog_ajouter:
    pattern:    /ajouter
    defaults:    { _controller: SdzBlogBundle:Blog:ajouter }

sdzblog_modifier:
    pattern:    /modifier/{id}
    defaults:    { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        id:    \d+

sdzblog_supprimer:
    pattern:    /supprimer/{id}
    defaults:    { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        id:    \d+
sdzblog_voir_slug:
    pattern:    /{annee}/{slug}.{format}
    defaults:    { _controller: SdzBlogBundle:Blog:voirSlug, format: html }
    requirements:
        annee:    \d{4}
        format:    html|xml